# touchdesigner-mcp bridge installer
#
# 使い方 (どちらでも OK):
#   A) TouchDesigner で Text DAT を作り、このファイルの中身を全部ペーストして
#      右クリック → "Run Script"
#   B) Textport (Alt+T / Dialogs > Textport and DATs) にペーストして実行
#
# 実行すると /mcp_bridge (Base COMP) が作られ、中の WebServer DAT が
# http://127.0.0.1:9981 で MCP サーバーからのリクエストを待ち受けます。
# 再実行すると既存のブリッジを最新のハンドラで上書きします (何度でも安全)。
#
# ポートを変えたい場合は下の PORT を変更し、MCP サーバー側では環境変数
# TD_WEBSERVER_URL (例: http://127.0.0.1:9999) を設定してください。

PORT = 9981
COMP_NAME = 'mcp_bridge'

HANDLER_CODE = '''# TouchDesigner MCP bridge - WebServer DAT callbacks
# Generated by setup_mcp.py. Speaks JSON over HTTP with the touchdesigner-mcp
# Node.js server: POST /api {"cmd": ..., "args": {...}} -> {"ok": ..., "result": ...}

import base64
import fnmatch
import io
import json
import sys
import traceback

MAX_LIST = 500
MAX_ISSUES = 200


def _err(msg):
    raise ValueError(msg)


def _op_or_fail(path):
    o = op(path)
    if o is None:
        _err('Operator not found: {}. Use td_list_operators to inspect the network.'.format(path))
    return o


def _op_summary(o):
    info = {'path': o.path, 'name': o.name, 'family': o.family}
    try:
        info['opType'] = o.OPType
    except Exception:
        info['opType'] = o.type
    if o.isCOMP:
        try:
            info['numChildren'] = len(o.children)
        except Exception:
            pass
    try:
        e = o.errors(recurse=False)
        if e:
            info['errors'] = e
    except Exception:
        pass
    return info


def _par_info(p):
    d = {'name': p.name, 'label': p.label, 'style': p.style}
    try:
        v = p.eval()
        if not isinstance(v, (int, float, str, bool, type(None))):
            v = str(v)
        d['value'] = v
    except Exception:
        d['value'] = None
    try:
        m = p.mode.name
        if m != 'CONSTANT':
            d['mode'] = m
        if m == 'EXPRESSION':
            d['expr'] = p.expr
    except Exception:
        pass
    return d


def _apply_pars(o, pars):
    applied = []
    for name, value in pars.items():
        matched = o.pars(name)
        if not matched:
            available = ', '.join(p.name for p in o.pars()[:60])
            _err("Parameter '{}' not found on {}. Available parameters: {}".format(
                name, o.path, available))
        if isinstance(value, dict) and 'expr' in value:
            for p in matched:
                p.expr = str(value['expr'])
        elif isinstance(value, (list, tuple)):
            if len(matched) != len(value):
                _err("Pattern '{}' matched {} parameters ({}) but {} values were given".format(
                    name, len(matched), ', '.join(p.name for p in matched), len(value)))
            for p, v in zip(matched, value):
                p.val = v
        else:
            for p in matched:
                p.val = value
        applied.extend(p.name for p in matched)
    return applied


def _info(args):
    d = {}
    try:
        d['product'] = app.product
        d['version'] = app.version
        d['build'] = app.build
        d['osName'] = app.osName
    except Exception:
        pass
    try:
        d['projectName'] = project.name
        d['projectFolder'] = project.folder
    except Exception:
        pass
    try:
        d['fps'] = project.cookRate
        d['frame'] = absTime.frame
    except Exception:
        pass
    return d


def _list_ops(args):
    parent = _op_or_fail(args.get('parent') or '/')
    if not parent.isCOMP:
        _err('{} is not a COMP; it has no children.'.format(parent.path))
    depth = int(args.get('depth') or 1)
    if depth <= 1:
        found = list(parent.children)
    else:
        found = list(parent.findChildren(maxDepth=depth))
    family = args.get('family')
    if family:
        found = [o for o in found if o.family == family]
    pattern = args.get('namePattern')
    if pattern:
        found = [o for o in found if fnmatch.fnmatch(o.name, pattern)]
    truncated = len(found) > MAX_LIST
    found = found[:MAX_LIST]
    return {'operators': [_op_summary(o) for o in found], 'truncated': truncated}


def _get_op(args):
    o = _op_or_fail(args['path'])
    info = _op_summary(o)
    try:
        w = o.warnings(recurse=False)
        if w:
            info['warnings'] = w
    except Exception:
        pass
    try:
        info['inputs'] = [i.path for i in o.inputs]
        info['outputs'] = [x.path for x in o.outputs]
    except Exception:
        pass
    if o.family == 'TOP':
        info['width'] = o.width
        info['height'] = o.height
    if args.get('includeParameters', True):
        info['parameters'] = [_par_info(p) for p in o.pars()]
    return info


def _create_op(args):
    parent = _op_or_fail(args.get('parent') or '/')
    optype = args['opType']
    name = args.get('name')
    try:
        new_op = parent.create(optype, name) if name else parent.create(optype)
    except Exception:
        import td
        cls = getattr(td, optype, None)
        if cls is None:
            _err("Unknown opType '{}'. Use TouchDesigner Python class names such as "
                 "noiseTOP, moviefileinTOP, levelTOP, constantCHOP, geoCOMP, textDAT.".format(optype))
        new_op = parent.create(cls, name) if name else parent.create(cls)
    if args.get('nodeX') is not None:
        new_op.nodeX = args['nodeX']
    if args.get('nodeY') is not None:
        new_op.nodeY = args['nodeY']
    pars = args.get('parameters') or {}
    if pars:
        _apply_pars(new_op, pars)
    return _op_summary(new_op)


def _set_pars(args):
    o = _op_or_fail(args['path'])
    applied = _apply_pars(o, args.get('parameters') or {})
    return {'path': o.path, 'applied': applied}


def _delete_op(args):
    o = _op_or_fail(args['path'])
    path = o.path
    o.destroy()
    return {'deleted': path}


def _connect(args):
    src = _op_or_fail(args['fromPath'])
    dst = _op_or_fail(args['toPath'])
    oi = int(args.get('fromOutput') or 0)
    ii = int(args.get('toInput') or 0)
    if src.parent() != dst.parent():
        _err('{} and {} are in different networks; they cannot be wired directly.'.format(
            src.path, dst.path))
    if oi >= len(src.outputConnectors):
        _err('{} has only {} output connector(s).'.format(src.path, len(src.outputConnectors)))
    if ii >= len(dst.inputConnectors):
        _err('{} has only {} input connector(s).'.format(dst.path, len(dst.inputConnectors)))
    src.outputConnectors[oi].connect(dst.inputConnectors[ii])
    return {'connected': '{}[{}] -> {}[{}]'.format(src.path, oi, dst.path, ii)}


def _capture_top(args):
    t = _op_or_fail(args['path'])
    if t.family != 'TOP':
        _err('{} is a {}, not a TOP. Pass the path of a TOP (e.g. an out1 or null TOP).'.format(
            t.path, t.family))
    max_width = args.get('maxWidth')
    target = t
    tmp = None
    try:
        if max_width and t.width > int(max_width):
            try:
                tmp = t.parent().create('resizeTOP')
                tmp.par.outputresolution = 'custom'
                tmp.par.resolutionw = int(max_width)
                tmp.par.resolutionh = max(1, int(t.height * int(max_width) / max(1, t.width)))
                tmp.inputConnectors[0].connect(t.outputConnectors[0])
                tmp.cook(force=True)
                target = tmp
            except Exception:
                target = t
        w = target.width
        h = target.height
        data = bytes(target.saveByteArray('.png'))
    finally:
        if tmp is not None:
            try:
                tmp.destroy()
            except Exception:
                pass
    return {'imageBase64': base64.b64encode(data).decode('ascii'),
            'width': w, 'height': h, 'format': 'png'}


def _get_errors(args):
    parent = _op_or_fail(args.get('parent') or '/')
    issues = []
    for o in parent.findChildren():
        try:
            e = o.errors(recurse=False)
        except Exception:
            e = ''
        try:
            w = o.warnings(recurse=False)
        except Exception:
            w = ''
        if e or w:
            item = _op_summary(o)
            if e:
                item['errors'] = e
            if w:
                item['warnings'] = w
            issues.append(item)
        if len(issues) >= MAX_ISSUES:
            break
    return {'count': len(issues), 'issues': issues}


def _exec_python(args):
    code = args['code']
    buf = io.StringIO()
    old_stdout = sys.stdout
    sys.stdout = buf
    result = None
    try:
        try:
            result = eval(code, globals())
        except SyntaxError:
            exec(code, globals())
    finally:
        sys.stdout = old_stdout
    out = {'stdout': buf.getvalue()}
    if result is not None:
        out['result'] = repr(result)
    return out


_COMMANDS = {
    'info': _info,
    'exec': _exec_python,
    'list_ops': _list_ops,
    'get_op': _get_op,
    'create_op': _create_op,
    'set_pars': _set_pars,
    'delete_op': _delete_op,
    'connect': _connect,
    'capture_top': _capture_top,
    'get_errors': _get_errors,
}


def onHTTPRequest(webServerDAT, request, response):
    response['Content-Type'] = 'application/json'
    response['statusCode'] = 200
    response['statusReason'] = 'OK'
    uri = request.get('uri', '')
    if request.get('method') == 'GET':
        response['data'] = json.dumps({'ok': True, 'result': {
            'service': 'touchdesigner-mcp bridge',
            'commands': sorted(_COMMANDS)}})
        return response
    if uri != '/api':
        response['statusCode'] = 404
        response['statusReason'] = 'Not Found'
        response['data'] = json.dumps({'ok': False, 'error': 'Unknown endpoint: {}'.format(uri)})
        return response
    try:
        raw = request.get('data') or b''
        if isinstance(raw, bytes):
            raw = raw.decode('utf-8')
        payload = json.loads(raw or '{}')
        cmd = payload.get('cmd')
        handler = _COMMANDS.get(cmd)
        if handler is None:
            _err('Unknown cmd: {}. Available: {}'.format(cmd, ', '.join(sorted(_COMMANDS))))
        result = handler(payload.get('args') or {})
        response['data'] = json.dumps({'ok': True, 'result': result})
    except Exception as e:
        response['data'] = json.dumps({'ok': False, 'error': str(e),
                                       'traceback': traceback.format_exc()})
    return response
'''


def _install():
    root_comp = op('/')
    comp = root_comp.op(COMP_NAME)
    if comp is None:
        comp = root_comp.create('baseCOMP', COMP_NAME)
        comp.nodeX = 0
        comp.nodeY = -400

    callbacks = comp.op('mcp_callbacks')
    if callbacks is None:
        callbacks = comp.create('textDAT', 'mcp_callbacks')
        callbacks.nodeX = 200
        callbacks.nodeY = 0
    callbacks.text = HANDLER_CODE

    ws = comp.op('mcp_webserver')
    if ws is None:
        ws = comp.create('webserverDAT', 'mcp_webserver')
        ws.nodeX = 0
        ws.nodeY = 0
    ws.par.port = PORT
    ws.par.callbacks = 'mcp_callbacks'
    # restart so a changed port / handler takes effect
    ws.par.active = False
    ws.par.active = True

    print('touchdesigner-mcp bridge installed at /{}'.format(COMP_NAME))
    print('Listening on http://127.0.0.1:{}'.format(PORT))
    print('You can now start the touchdesigner-mcp server (Claude).')


_install()
